### ISSUE TITLE
Proposal for better robustness of the Berghel-Roach algorithm

### ISSUE THREAD

**Issue by oahrens** [sp1ff/damerau-levenshtein#4]
The code has small weaknesses for certain special cases, namely if one of the two compared strings has the length `0` or this applies to both. Here is my suggestion to solve the problem:

1. The volatile, overwritable area of the array `fkp[]` must be initialized with `0` instead of `-inf` so that the code handles the special cases mentioned correctly. To do this, the following changes must be made **(file br.hh)**:

    - Delete lines 137-141.

    - The complete initialization then takes place in the two nested loops lines 142-154, which must be supplemented as follows:
    ```
    for (ptrdiff_t k = - zero_k; k <= zero_k; ++k) {
        ptrdiff_t abs_k = k;
        if (k < 0) abs_k = -k;
        for (ptrdiff_t p = -1; p <= (ptrdiff_t)inf; ++p) {
            if (p == abs_k - 1) {
                if (k < 0) {
                    fkp[(k + zero_k) * max_p + p + 1] = abs_k - 1;
                } else {
                    fkp[(k + zero_k) * max_p + p + 1] = -1;
                }
            } else if (p < abs_k) {
                fkp[(k + zero_k) * max_p + p + 1] = -inf;
            } else {
                fkp[(k + zero_k) * max_p + p + 1] = 0;
            }
        }
    }
    ```

2. To prevent memory access errors that occure when reading outside the memory area reserved for `fkp[]` in the cases mentioned, two calls within `f()` **(file br.cc)** must be further restricted.
    Lines 50-53 becomes to:
   ```
    ptrdiff_t ta = -inf;
    if (p >= 0 && k > -zero_k) { // 'p >= 0 &&' can be omitted if the changes from issue#3 have been applied
       ta = fkp[(k - 1 + zero_k) * max_p + p];
    }
    ```
    Lines 54-57 becomes to:
    ```
    ptrdiff_t tb = -inf;
    if (p >= 0 && k < zero_k) { // 'p >= 0 &&' can be omitted if the changes from issue#3 have been applied
        tb = fkp[(k + 1 + zero_k) * max_p + p] + 1;
    }
    ```

Best greetings
Olaf

**Comment by sp1ff** [comment]
Going to close this one out after my last commit. If you think there's still an issue, would you consider cutting a PR? It's easier to look at code differences than textual descriptions.
